version: '3'
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-13T07-53-03Z
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin12345678
    user: "${UID}:${GID}"

networks:
  dev-env:
    external: true

